/**
 * Zod schemas mirroring `supabase/migrations/0001_schema.sql`, one per entity.
 *
 * Conventions:
 * - Server-managed audit columns (`id`, `created_at`, `updated_at`) are
 *   omitted — they're never supplied by a form, only generated by the DB.
 * - `posts.reading_minutes` is likewise omitted: it's derived from `content`
 *   via `readingMinutes()` (see `./format.ts`), not user input.
 * - Nullable DB columns accept `""` / missing and normalize to `null`.
 * - `not null default ''` text columns accept missing and default to `""`.
 * - Columns typed `text[]` in the DB (`tags`, `highlights`) accept either a
 *   comma-separated string (as sent by a plain HTML form) or a string array,
 *   and always resolve to a trimmed, non-empty string array.
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------

/** `"" | null | undefined` -> `null`, otherwise pass through. */
const nullifyEmpty = (val: unknown) => (val === "" || val == null ? null : val);

/** `"" | undefined` -> `undefined`, otherwise pass through (for optional non-nullable text). */
const undefineEmpty = (val: unknown) => (val === "" ? undefined : val);

/** Comma-separated string OR string[] -> trimmed, non-empty string[]. */
const csvToArray = (val: unknown): string[] => {
  const parts = Array.isArray(val) ? val.map(String) : typeof val === "string" ? val.split(",") : [];
  return parts.map((s) => s.trim()).filter(Boolean);
};

/** Optional nullable URL: `""`/missing -> `null`, otherwise must be a valid URL. */
const optionalUrl = () => z.preprocess(nullifyEmpty, z.string().trim().url().nullable().default(null));

/** Optional nullable plain text column. */
const optionalText = () => z.preprocess(nullifyEmpty, z.string().trim().nullable().default(null));

/** `not null default ''` text column: missing -> `""`. */
const defaultedText = () => z.preprocess(undefineEmpty, z.string().trim().default(""));

/** Tags/highlights style `text[]` column. */
const stringArray = () => z.preprocess(csvToArray, z.array(z.string()));

/** `date` column (start/end dates): plain `YYYY-MM-DD` (or ISO) string. */
const dateOnly = () => z.string().trim().min(1);

/** Nullable `date` column. */
const optionalDate = () => z.preprocess(nullifyEmpty, z.string().trim().nullable().default(null));

const sortOrder = () => z.coerce.number().int().default(0);

const statusEnum = () => z.enum(["draft", "published"]).default("draft");

// ---------------------------------------------------------------------------
// profile
// ---------------------------------------------------------------------------

export const profileSchema = z.object({
  full_name: z.string().trim().min(1, "Full name is required"),
  title: defaultedText(),
  headline: defaultedText(),
  bio: defaultedText(),
  avatar_url: optionalUrl(),
  resume_url: optionalUrl(),
  location: optionalText(),
  email: z.preprocess(nullifyEmpty, z.email().nullable().default(null)),
  phone: optionalText(),
  socials: z
    .object({
      github: z.preprocess(undefineEmpty, z.string().trim().optional()),
      linkedin: z.preprocess(undefineEmpty, z.string().trim().optional()),
      twitter: z.preprocess(undefineEmpty, z.string().trim().optional()),
      website: z.preprocess(undefineEmpty, z.string().trim().optional()),
    })
    .catchall(z.string())
    .default({}),
});
export type ProfileInput = z.infer<typeof profileSchema>;

// ---------------------------------------------------------------------------
// site_sections
// ---------------------------------------------------------------------------

export const sectionSchema = z.object({
  key: z.enum(["about", "experience", "skills", "projects", "achievements", "education", "contact"]),
  label: z.string().trim().min(1, "Label is required"),
  enabled: z.boolean().default(true),
  sort_order: sortOrder(),
});
export type SectionInput = z.infer<typeof sectionSchema>;

// ---------------------------------------------------------------------------
// projects
// ---------------------------------------------------------------------------

const slugField = z
  .string()
  .trim()
  .min(1, "Slug is required")
  .regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Slug must be lowercase, alphanumeric, and hyphen-separated");

export const projectSchema = z.object({
  title: z.string().trim().min(1, "Title is required"),
  slug: slugField,
  summary: defaultedText(),
  content: defaultedText(), // sanitized separately via sanitizeHtml() before persisting
  cover_image_url: optionalUrl(),
  tags: stringArray(),
  links: z
    .object({
      live: z.preprocess(undefineEmpty, z.string().trim().url().optional()),
      repo: z.preprocess(undefineEmpty, z.string().trim().url().optional()),
    })
    .default({}),
  featured: z.boolean().default(false),
  status: statusEnum(),
  sort_order: sortOrder(),
  published_at: optionalDate(),
});
export type ProjectInput = z.infer<typeof projectSchema>;

// ---------------------------------------------------------------------------
// experiences
// ---------------------------------------------------------------------------

export const experienceSchema = z
  .object({
    role: z.string().trim().min(1, "Role is required"),
    company: z.string().trim().min(1, "Company is required"),
    location: optionalText(),
    start_date: dateOnly(),
    end_date: optionalDate(),
    is_current: z.boolean().default(false),
    highlights: stringArray(),
    sort_order: sortOrder(),
  })
  .refine((data) => data.is_current || data.end_date !== null, {
    message: "End date is required unless this is the current role",
    path: ["end_date"],
  });
export type ExperienceInput = z.infer<typeof experienceSchema>;

// ---------------------------------------------------------------------------
// skills
// ---------------------------------------------------------------------------

export const skillSchema = z.object({
  name: z.string().trim().min(1, "Name is required"),
  category: z.preprocess(undefineEmpty, z.string().trim().default("General")),
  sort_order: sortOrder(),
});
export type SkillInput = z.infer<typeof skillSchema>;

// ---------------------------------------------------------------------------
// achievements
// ---------------------------------------------------------------------------

export const achievementSchema = z.object({
  title: z.string().trim().min(1, "Title is required"),
  description: defaultedText(),
  sort_order: sortOrder(),
});
export type AchievementInput = z.infer<typeof achievementSchema>;

// ---------------------------------------------------------------------------
// education
// ---------------------------------------------------------------------------

export const educationSchema = z.object({
  degree: z.string().trim().min(1, "Degree is required"),
  institution: z.string().trim().min(1, "Institution is required"),
  location: optionalText(),
  start_date: optionalDate(),
  end_date: optionalDate(),
  description: defaultedText(),
  sort_order: sortOrder(),
});
export type EducationInput = z.infer<typeof educationSchema>;

// ---------------------------------------------------------------------------
// posts
// ---------------------------------------------------------------------------

export const postSchema = z.object({
  title: z.string().trim().min(1, "Title is required"),
  slug: slugField,
  excerpt: defaultedText(),
  content: defaultedText(), // sanitized separately via sanitizeHtml() before persisting
  cover_image_url: optionalUrl(),
  tags: stringArray(),
  status: statusEnum(),
  published_at: optionalDate(),
});
export type PostInput = z.infer<typeof postSchema>;

// ---------------------------------------------------------------------------
// contact_messages (+ honeypot, not persisted)
// ---------------------------------------------------------------------------

export const contactSchema = z.object({
  name: z.string().trim().min(1, "Name is required"),
  email: z.email("Enter a valid email address"),
  message: z.string().trim().min(1, "Message is required"),
  // Spam-trap field: real users never fill this in (hidden via CSS). Any
  // non-empty value marks the submission as bot traffic and fails validation.
  honeypot: z.string().max(0, "Spam check failed").default(""),
});
export type ContactInput = z.infer<typeof contactSchema>;
